// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT3b-K_S5ySbSedJ72Xu_vPPAoEwjRxqY',
    appId: '1:732160365931:web:61e40b76959e08d4d7e82e',
    messagingSenderId: '732160365931',
    projectId: 'arfr-2f7c6',
    authDomain: 'arfr-2f7c6.firebaseapp.com',
    storageBucket: 'arfr-2f7c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrt-gaV10Jlyq8c5qw5vmXpuFHmZ99AsE',
    appId: '1:732160365931:android:ed3d6b292a1e067cd7e82e',
    messagingSenderId: '732160365931',
    projectId: 'arfr-2f7c6',
    storageBucket: 'arfr-2f7c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfc7-2Qrf__7F1itM7tslm2Wi9Ymq1hQ',
    appId: '1:732160365931:ios:97d777a09d28c530d7e82e',
    messagingSenderId: '732160365931',
    projectId: 'arfr-2f7c6',
    storageBucket: 'arfr-2f7c6.appspot.com',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABfc7-2Qrf__7F1itM7tslm2Wi9Ymq1hQ',
    appId: '1:732160365931:ios:97d777a09d28c530d7e82e',
    messagingSenderId: '732160365931',
    projectId: 'arfr-2f7c6',
    storageBucket: 'arfr-2f7c6.appspot.com',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT3b-K_S5ySbSedJ72Xu_vPPAoEwjRxqY',
    appId: '1:732160365931:web:4bf7bfaf197b4c89d7e82e',
    messagingSenderId: '732160365931',
    projectId: 'arfr-2f7c6',
    authDomain: 'arfr-2f7c6.firebaseapp.com',
    storageBucket: 'arfr-2f7c6.appspot.com',
  );
}
